// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_testshim is a generated GoMock package.
package mock_testshim

import (
	context "context"
	reflect "reflect"
	gomock "github.com/golang/mock/gomock"

	testapi "github.com/snyk/go-application-framework/pkg/apiclients/testapi"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// StartTest mocks base method.
func (m *MockClient) StartTest(ctx context.Context, params testapi.StartTestParams) (testapi.TestHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTest", ctx, params)
	ret0, _ := ret[0].(testapi.TestHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTest indicates an expected call of StartTest.
func (mr *MockClientMockRecorder) StartTest(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTest", reflect.TypeOf((*MockClient)(nil).StartTest), ctx, params)
}
