// Code generated by MockGen. DO NOT EDIT.
// Source: vendor/github.com/snyk/go-application-framework/pkg/apiclients/fileupload/client.go

// Package clients is a generated GoMock package.
package clients

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"

	"github.com/snyk/go-application-framework/pkg/apiclients/fileupload"
)

// MockFileUploadClient is a mock of FileUpload interface.
type MockFileUploadClient struct {
	ctrl     *gomock.Controller
	recorder *MockFileUploadClientMockRecorder
}

// MockFileUploadClientMockRecorder is the mock recorder for MockFileUploadClient.
type MockFileUploadClientMockRecorder struct {
	mock *MockFileUploadClient
}

// NewMockFileUploadClient creates a new mock instance.
func NewMockFileUploadClient(ctrl *gomock.Controller) *MockFileUploadClient {
	mock := &MockFileUploadClient{ctrl: ctrl}
	mock.recorder = &MockFileUploadClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUploadClient) EXPECT() *MockFileUploadClientMockRecorder {
	return m.recorder
}

// CreateRevisionFromChan mocks base method.
func (m *MockFileUploadClient) CreateRevisionFromChan(ctx context.Context, paths <-chan string, baseDir string) (fileupload.UploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRevisionFromChan", ctx, paths, baseDir)
	ret0, _ := ret[0].(fileupload.UploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRevisionFromChan indicates an expected call of CreateRevisionFromChan.
func (mr *MockFileUploadClientMockRecorder) CreateRevisionFromChan(ctx, paths, baseDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRevisionFromChan", reflect.TypeOf((*MockFileUploadClient)(nil).CreateRevisionFromChan), ctx, paths, baseDir)
}
