// Code generated by MockGen. DO NOT EDIT.
// Source: vendor/github.com/snyk/go-application-framework/pkg/apiclients/testapi/client.go

// Package clients is a generated GoMock package.
package clients

import (
	"github.com/golang/mock/gomock"
)

// MockTestShimClient is a mock of TestShimClient interface.
type MockTestShimClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestShimClientMockRecorder
}

// MockTestShimClientMockRecorder is the mock recorder for MockTestShimClient.
type MockTestShimClientMockRecorder struct {
	mock *MockTestShimClient
}

// NewMockTestShimClient creates a new mock instance.
func NewMockTestShimClient(ctrl *gomock.Controller) *MockTestShimClient {
	mock := &MockTestShimClient{ctrl: ctrl}
	mock.recorder = &MockTestShimClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestShimClient) EXPECT() *MockTestShimClientMockRecorder {
	return m.recorder
}
