// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_upload is a generated GoMock package.
package mock_upload

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	fileupload "github.com/snyk/go-application-framework/pkg/apiclients/fileupload"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateRevisionFromChan mocks base method.
func (m *MockClient) CreateRevisionFromChan(ctx context.Context, paths <-chan string, baseDir string) (fileupload.UploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRevisionFromChan", ctx, paths, baseDir)
	ret0, _ := ret[0].(fileupload.UploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRevisionFromChan indicates an expected call of CreateRevisionFromChan.
func (mr *MockClientMockRecorder) CreateRevisionFromChan(ctx, paths, baseDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRevisionFromChan", reflect.TypeOf((*MockClient)(nil).CreateRevisionFromChan), ctx, paths, baseDir)
}
